#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1328908841                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get better, stronger & maintain your fitness with a routine using this app. Track your workouts & exercises in a simple & intuitively designed app just for you.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nishan Niraula                               
your_link                                 : https://twitter.com/nrlnishan
your_city                                 : 
email_address                             : gymdiaryios@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : gym_diary_ios
github_username                           : nrlnishan
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Beautiful User Interface
    description                           : No more clunky, difficult navigation. Easy to use app with beautiful UI and with Dark Mode.
    fontawesome_icon_name                 : palette
    
  - title                                 : Custom Exercises
    description                           : "Create your own unlimited exercises for free. No more overwhelming unnecessary exercises which you don't know about. Create exercises as you progress"
    fontawesome_icon_name                 : dumbbell

  - title                                 : Workout Plan
    description                           : Plan your workout ahead, create a draft for your workout & simply track it with single tap.
    fontawesome_icon_name                 : file-alt

  - title                                 : Progress Graph
    description                           : "Just the graph you need. No unnecessary complicated graph to show your progress that you don't understand."
    fontawesome_icon_name                 : chart-line

  - title                                 : Custom App Icons
    description                           : Want to stand out from the crowd? You can choose from multiple app icons.
    fontawesome_icon_name                 : mobile
  
  - title                                 : Data Backup
    description                           : "Your workout data gets backed up to your icloud account automatically so that you won't lose it ever."
    fontawesome_icon_name                 : sync

  - title                                 : Calories Tracking
    description                           : Track your daily calorie input
    fontawesome_icon_name                 : fire-alt

  - title                                 : Body Measurements
    description                           : Measure size of various body parts related to your workouts & keep track of the progress.
    fontawesome_icon_name                 : ruler

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
